name: Publish Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '.github/workflows/release.yaml'

permissions:
  contents: write  # needed to push changes to gh-pages

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.0
      
      - name: Add dependency chart repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add kong https://charts.konghq.com

      - name: Build chart dependencies
        run: |
          cd kong
          helm dependency build

      - name: Package chart
        run: |
          mkdir -p docs
          cd kong
          helm package . -d ../docs

      - name: Update Helm repo index
        run: |
          helm repo index docs --url https://shiponcs.github.io/charts

      - name: Commit and push chart repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Publish Helm chart [skip ci]" || echo "No changes to commit"
          git push origin main
